import requests

# Substitua pelo token que você obteve na autenticação web
access_token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkpETmFfNGk0cjdGZ2lnTDNzSElsSTN4Vi1JVSIsImtpZCI6IkpETmFfNGk0cjdGZ2lnTDNzSElsSTN4Vi1JVSJ9.eyJhdWQiOiJodHRwczovL2FwaS5mYWJyaWMubWljcm9zb2Z0LmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzY2NTNiMjBhLWVkYjYtNDRlOS1iMjVmLWUyOGMxNDY3OWYxZC8iLCJpYXQiOjE3NDE3MTA3ODMsIm5iZiI6MTc0MTcxMDc4MywiZXhwIjoxNzQxNzE2MzIyLCJhY2N0IjowLCJhY3IiOiIxIiwiYWlvIjoiQVdRQW0vOFpBQUFBYlNkWS9GYUJCR0o2ME41NFp6S1lFRWtCYitjUzhkd0JpWHdyM0xhQ0ZsdGR5TTNVRU5GZFlZM29jajRZTHEyb0tVaUc5VXhWRUEwbzFibUJLWXM2WWdUWk5lYWtSTUtoaEF2UkJlSitVMTVqUkZDSWIyT25vQnR3ejFvd203eTgiLCJhbXIiOlsicHdkIiwicnNhIl0sImFwcGlkIjoiMDNmMTJkZGItYzQ3YS00MjBlLWJjZWItMGU2YThjY2RmYWFkIiwiYXBwaWRhY3IiOiIxIiwiZGV2aWNlaWQiOiIzN2IzZjlkMi1hMDBlLTRkMTEtYTZiOS1mNTA1ZGFlNjlmZDMiLCJmYW1pbHlfbmFtZSI6ImRhIFNpbHZhIiwiZ2l2ZW5fbmFtZSI6Ik1hbm9lbCBNYXJjb3MiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIyODA0OjI5Yjg6NTE1YTphNWE1OjkxODU6MzVjYjo2OThiOjIzN2QiLCJuYW1lIjoiTWFub2VsIE1hcmNvcyBkYSBTaWx2YSIsIm9pZCI6IjA1MDIxNjhjLTZkMWItNDllNC05YzQwLWNjNjBjM2Y5ZjYyMCIsInB1aWQiOiIxMDAzMjAwMkEzRkMxQTc3IiwicmgiOiIxLkFWQUFDckpUWnJidDZVU3lYLUtNRkdlZkhRa0FBQUFBQUFBQXdBQUFBQUFBQUFELUFPbFFBQS4iLCJzY3AiOiJEYXRhc2V0LlJlYWQuQWxsIERhdGFzZXQuUmVhZFdyaXRlLkFsbCBSZXBvcnQuUmVhZC5BbGwgUmVwb3J0LlJlYWRXcml0ZS5BbGwgV29ya3NwYWNlLlJlYWQuQWxsIFdvcmtzcGFjZS5SZWFkV3JpdGUuQWxsIiwic2lkIjoiMDAyMTRiODktMGFiMC0xY2YyLWEzOWYtZjBiZTdkNmJkNzc4Iiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoiT18xV0EtdkY1U1VacF9tbFJhSEZmWU5UVlRGOWJLUk9kTFl4czE5M3plbyIsInRpZCI6IjY2NTNiMjBhLWVkYjYtNDRlOS1iMjVmLWUyOGMxNDY3OWYxZCIsInVuaXF1ZV9uYW1lIjoibWFub2VsLm1hcmNvc0A1OHE0eXMub25taWNyb3NvZnQuY29tIiwidXBuIjoibWFub2VsLm1hcmNvc0A1OHE0eXMub25taWNyb3NvZnQuY29tIiwidXRpIjoic0dLd1dTcEhURWk4bklER1ZkMDFBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiNjJlOTAzOTQtNjlmNS00MjM3LTkxOTAtMDEyMTc3MTQ1ZTEwIiwiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19pZHJlbCI6IjEgMTYiLCJ4bXNfcGwiOiJlbiJ9.cturmVFZMNtp5ZFVrk1jLbPoD_XTeyf6IX26aai4oHQSZgstqVPkP-Y9CJmn0pH7ZkD1C5oB2FEZZw77bAcysrc6WXQN3k8nOlwc0FVFEtvN9vQFGr1mTkW0iDrEvpvneT0wxY9SHciErOittZbi5Say28RmU0WzfbpRpCzWPLxuxgdepsIHSc2kqzdPVi4W_6UHfEE7r1v_GaxvySqW0wHKCie2_s48Bn9WKDTZTflR6qlT_B0LGBBxcM54ZN-VapwB7IiGyB0lkAc2znIVXxxeU200AtMtHjAEn_d5VLTiLYEDaHhO0lwOUWIjBxiBENOZHL-2vGdWDAkoNZE5rw"

# URL da API para listar os workspaces
url = "https://api.fabric.microsoft.com/v1/workspaces"

# Cabeçalhos com o token de autorização
headers = {
    "Authorization": f"Bearer {access_token}",
    "Content-Type": "application/json"
}

# Fazendo a requisição GET
response = requests.get(url, headers=headers)

# Exibindo os dados dos workspaces
if response.status_code == 200:
    print("🔹 Workspaces disponíveis:")
    print(response.json())
else:
    print(f"❌ Erro ao obter workspaces: {response.status_code}")
    print(response.text)
